name: docs-ci 

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - docs/*
      - .github/workflows/docs.yml
      - mkdocs.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-video markdown-include
      - run: mkdocs gh-deploy --force
